// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace Web_Projekat_Sah.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Models.Igrac", b =>
                {
                    b.Property<int>("IgracID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Datum_rodjenja")
                        .HasColumnType("datetime2");

                    b.Property<int>("Fide")
                        .HasMaxLength(6)
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("KlubID")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Rejting")
                        .HasColumnType("int");

                    b.Property<int>("Titula")
                        .HasColumnType("int");

                    b.Property<int?>("TurnirID")
                        .HasColumnType("int");

                    b.Property<int?>("TurnirID1")
                        .HasColumnType("int");

                    b.HasKey("IgracID");

                    b.HasIndex("KlubID");

                    b.HasIndex("TurnirID");

                    b.HasIndex("TurnirID1");

                    b.ToTable("Igrac");
                });

            modelBuilder.Entity("Models.Klub", b =>
                {
                    b.Property<int>("KlubID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Broj_Igraca")
                        .HasColumnType("int");

                    b.Property<string>("Broj_Telefona")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Mesto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("KlubID");

                    b.ToTable("Klub");
                });

            modelBuilder.Entity("Models.Mec", b =>
                {
                    b.Property<int>("MecID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("BeliIgracID")
                        .HasColumnType("int");

                    b.Property<int?>("CrniIgracID")
                        .HasColumnType("int");

                    b.Property<int>("Kolo")
                        .HasColumnType("int");

                    b.Property<int>("Result")
                        .HasColumnType("int");

                    b.Property<int>("TurnirID")
                        .HasColumnType("int");

                    b.HasKey("MecID");

                    b.HasIndex("BeliIgracID");

                    b.HasIndex("CrniIgracID");

                    b.HasIndex("TurnirID");

                    b.ToTable("Mec");
                });

            modelBuilder.Entity("Models.Sudija", b =>
                {
                    b.Property<int>("SudijaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Kategorija")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("SudijaID");

                    b.ToTable("Sudija");
                });

            modelBuilder.Entity("Models.Turnir", b =>
                {
                    b.Property<int>("TurnirID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Datum_pocetka")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Klub_organizatorKlubID")
                        .HasColumnType("int");

                    b.Property<string>("Mesto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Nagrada")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PobednikIgracID")
                        .HasColumnType("int");

                    b.Property<int?>("SudijaID")
                        .HasColumnType("int");

                    b.HasKey("TurnirID");

                    b.HasIndex("Klub_organizatorKlubID");

                    b.HasIndex("PobednikIgracID");

                    b.HasIndex("SudijaID");

                    b.ToTable("Turnir");
                });

            modelBuilder.Entity("Models.Igrac", b =>
                {
                    b.HasOne("Models.Klub", "Klub")
                        .WithMany("Igraci")
                        .HasForeignKey("KlubID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Turnir", null)
                        .WithMany("Ostali_igraci")
                        .HasForeignKey("TurnirID");

                    b.HasOne("Models.Turnir", null)
                        .WithMany("Prijavljeni_igraci")
                        .HasForeignKey("TurnirID1");

                    b.Navigation("Klub");
                });

            modelBuilder.Entity("Models.Mec", b =>
                {
                    b.HasOne("Models.Igrac", "Beli")
                        .WithMany()
                        .HasForeignKey("BeliIgracID");

                    b.HasOne("Models.Igrac", "Crni")
                        .WithMany()
                        .HasForeignKey("CrniIgracID");

                    b.HasOne("Models.Turnir", "Turnir")
                        .WithMany("Mecevi")
                        .HasForeignKey("TurnirID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beli");

                    b.Navigation("Crni");

                    b.Navigation("Turnir");
                });

            modelBuilder.Entity("Models.Turnir", b =>
                {
                    b.HasOne("Models.Klub", "Klub_organizator")
                        .WithMany()
                        .HasForeignKey("Klub_organizatorKlubID");

                    b.HasOne("Models.Igrac", "Pobednik")
                        .WithMany()
                        .HasForeignKey("PobednikIgracID");

                    b.HasOne("Models.Sudija", "Sudija")
                        .WithMany("Sudjeni_turniri")
                        .HasForeignKey("SudijaID");

                    b.Navigation("Klub_organizator");

                    b.Navigation("Pobednik");

                    b.Navigation("Sudija");
                });

            modelBuilder.Entity("Models.Klub", b =>
                {
                    b.Navigation("Igraci");
                });

            modelBuilder.Entity("Models.Sudija", b =>
                {
                    b.Navigation("Sudjeni_turniri");
                });

            modelBuilder.Entity("Models.Turnir", b =>
                {
                    b.Navigation("Mecevi");

                    b.Navigation("Ostali_igraci");

                    b.Navigation("Prijavljeni_igraci");
                });
#pragma warning restore 612, 618
        }
    }
}
